/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/web/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/active-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setSessionArchived"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getComputeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/uploads/{upload_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commitUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}/events/{sequence}/attachments/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAttachmentCapability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/sessions/{session_id}/runs/{run_id}/artifact-manifests/{manifest_id}/artifacts/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getArtifactCapability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/attached-workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAttachedWorkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/attached-workers/{worker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAttachedWorker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/v1/attached-workers/{worker_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAttachedWorkerDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: components["schemas"]["PublicError"];
        };
        PublicError: {
            /** @enum {string} */
            code: "invalid_request" | "unauthenticated" | "access_denied" | "csrf_failed" | "not_found" | "conflict" | "payload_too_large" | "rate_limited" | "temporarily_unavailable";
            message: string;
            request_id: string;
        };
        TenantSummary: {
            tenant_id: string;
            /** @enum {string} */
            role: "owner" | "member" | "viewer";
            active: boolean;
        };
        TenantPage: {
            items: components["schemas"]["TenantSummary"][];
            next_cursor?: string;
        };
        Identity: {
            user_id: string;
            provider: string;
            tenants: components["schemas"]["TenantSummary"][];
        };
        SelectTenantRequest: {
            tenant_id: string;
        };
        /** @enum {string} */
        SessionStatus: "active" | "archived";
        SessionSummary: {
            session_id: string;
            status: components["schemas"]["SessionStatus"];
            title?: string;
            preview?: string;
            frontend_origin?: string;
            last_sequence: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            archived_at?: string;
            current_run?: components["schemas"]["Run"];
        };
        SessionPage: {
            items: components["schemas"]["SessionSummary"][];
            next_cursor?: string;
        };
        CreateSessionRequest: {
            idempotency_key: string;
        };
        ArchiveSessionRequest: {
            archived: boolean;
            idempotency_key: string;
        };
        Attachment: {
            name: string;
            media_type: string;
            size: number;
        };
        ArtifactManifest: {
            run_id: string;
            manifest_id: string;
        };
        EventContent: {
            text?: string;
            attachments?: components["schemas"]["Attachment"][];
            artifact_manifest?: components["schemas"]["ArtifactManifest"];
            data?: unknown;
        };
        SessionEvent: {
            event_id: string;
            sequence: number;
            /** @enum {string} */
            kind: "user_message" | "assistant_message" | "tool_call" | "tool_result" | "system_notice";
            content: components["schemas"]["EventContent"];
            /** Format: date-time */
            created_at: string;
        };
        EventPage: {
            items: components["schemas"]["SessionEvent"][];
            next_cursor?: string;
        };
        Run: {
            run_id: string;
            session_id: string;
            trigger_event_id: string;
            subscription_connection_id: string;
            provider?: string;
            /** @enum {string} */
            status: "created" | "admitted" | "queued" | "running" | "succeeded" | "failed" | "cancelled" | "quota_blocked";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            finished_at?: string;
        };
        RunPage: {
            items: components["schemas"]["Run"][];
            next_cursor?: string;
        };
        ComputeConnection: {
            provider: string;
            /** @enum {string} */
            entitlement: "disconnected" | "unknown" | "active" | "inactive" | "reauthentication_required";
            /** @enum {string} */
            quota: "unknown" | "available" | "limited" | "exhausted";
            /** Format: date-time */
            observed_at: string;
        };
        ComputeStatus: {
            /** @enum {string} */
            availability: "not_configured" | "ready" | "ambiguous";
            connection?: components["schemas"]["ComputeConnection"];
        };
        CreateMessageRequest: {
            idempotency_key: string;
            text?: string;
            upload_ids?: string[];
        };
        CreateMessageResponse: {
            session_id: string;
            event_id: string;
            sequence: number;
            run_id: string;
            created: boolean;
            compute: components["schemas"]["ComputeConnection"];
        };
        CreateUploadRequest: {
            session_id: string;
            idempotency_key: string;
            name: string;
            media_type: string;
            size: number;
            sha256: string;
            content_md5: string;
        };
        UploadIntent: {
            upload_id: string;
            /** @constant */
            method: "PUT";
            url: string;
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        CommitUploadRequest: {
            upload_id: string;
        };
        UploadCommit: {
            upload_id: string;
            name: string;
            media_type: string;
            size: number;
        };
        DownloadCapability: {
            /** @constant */
            method: "GET";
            url: string;
            headers?: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        AttachedWorkerFreshnessV1: "unknown" | "fresh" | "expired";
        /** @description Canonical unsigned 64-bit decimal string; encoded as text to preserve browser precision. */
        AttachedWorkerUint64V1: string;
        /** @enum {string} */
        AttachedWorkerReasonCodeV1: "worker_not_active" | "worker_revoked" | "worker_draining" | "worker_offline" | "connection_attaching" | "connection_superseded" | "presence_expired" | "authentication_expired" | "protocol_incompatible" | "capability_missing" | "capability_stale" | "capability_mismatch" | "policy_mismatch" | "isolation_unsupported" | "isolation_unverified" | "credential_unavailable" | "credential_reauth_required" | "entitlement_unknown" | "entitlement_inactive" | "quota_unknown" | "quota_zero" | "quota_exhausted" | "capacity_busy" | "attempt_active" | "attempt_ambiguous" | "control_contract_unavailable" | "backend_unavailable";
        /** @enum {string} */
        AttachedWorkerActionCodeV1: "create_enrollment" | "consume_enrollment" | "rename" | "rotate_identity" | "pause_admission" | "resume_admission" | "drain" | "revoke" | "request_cancel" | "reconnect_remediation" | "reauth_remediation" | "check_update" | "logout" | "uninstall_plan";
        /** @enum {string} */
        AttachedWorkerActionUnavailableCodeV1: "not_found" | "stale_revision" | "stale_generation" | "invalid_state" | "active_attempt" | "ambiguous_attempt" | "awaiting_acknowledgement" | "already_applied" | "unsupported_platform" | "feature_disabled" | "control_contract_unavailable" | "confirmation_required" | "operation_in_progress";
        AttachedWorkerIdentityRecordV1: {
            worker_id: string;
            display_name: string;
            revision: components["schemas"]["AttachedWorkerUint64V1"];
            enrollment_generation: components["schemas"]["AttachedWorkerUint64V1"];
            connection_generation: components["schemas"]["AttachedWorkerUint64V1"];
            desired_state: string;
            observed_state: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            revoked_at?: string;
        };
        AttachedWorkerIdentityV1: {
            algorithm: string;
            fingerprint: string;
            enrollment_state: string;
        };
        AttachedWorkerLastFailureV1: {
            state: string;
            code?: string;
            /** Format: date-time */
            occurred_at?: string;
            operation?: string;
            retry_class?: string;
            source?: string;
            freshness?: components["schemas"]["AttachedWorkerFreshnessV1"];
        };
        AttachedWorkerDaemonObservationV1: {
            state: string;
            source: string;
            /** Format: date-time */
            observed_at?: string;
            freshness: components["schemas"]["AttachedWorkerFreshnessV1"];
        };
        AttachedWorkerIsolationV1: {
            configuration_state: string;
            advertised_evidence: string[];
            verification_state: string;
        };
        AttachedWorkerReadinessV1: {
            daemon_observation: components["schemas"]["AttachedWorkerDaemonObservationV1"];
            last_daemon_failure: components["schemas"]["AttachedWorkerLastFailureV1"];
            credential_state: string;
            isolation: components["schemas"]["AttachedWorkerIsolationV1"];
        };
        AttachedWorkerConnectivityV1: {
            connection_id?: string;
            state: string;
            /** Format: date-time */
            connected_at?: string;
            /** Format: date-time */
            last_contact_at?: string;
            /** Format: date-time */
            presence_expires_at?: string;
            /** Format: date-time */
            authentication_expires_at?: string;
            freshness: components["schemas"]["AttachedWorkerFreshnessV1"];
            last_failure: components["schemas"]["AttachedWorkerLastFailureV1"];
        };
        AttachedWorkerHarnessV1: {
            name?: string;
            version?: string;
            surface?: string;
        };
        AttachedWorkerCapabilityV1: {
            state: string;
            manifest_revision?: components["schemas"]["AttachedWorkerUint64V1"];
            digest_fingerprint?: string;
            operating_system?: string;
            architecture?: string;
            build_id?: string;
            harness: components["schemas"]["AttachedWorkerHarnessV1"];
            isolation_evidence: string[];
            features: string[];
            max_concurrent_attempts?: number;
            /** Format: date-time */
            observed_at?: string;
        };
        AttachedWorkerAdmissionPreviewV1: {
            /** @enum {string} */
            state: "not_evaluated" | "admitted" | "denied";
            decision_code?: string;
            evaluation_ref?: string;
            candidate_ref?: string;
            /** Format: date-time */
            evaluated_at?: string;
            worker_revision?: components["schemas"]["AttachedWorkerUint64V1"];
            enrollment_generation?: components["schemas"]["AttachedWorkerUint64V1"];
            connection_generation?: components["schemas"]["AttachedWorkerUint64V1"];
            capability_digest_fingerprint?: string;
            policy_digest_fingerprint?: string;
            context_digest_fingerprint?: string;
        };
        AttachedWorkerQuotaObservationV1: {
            state: string;
            remaining?: components["schemas"]["AttachedWorkerUint64V1"];
            /** Format: date-time */
            observed_at?: string;
            /** Format: date-time */
            reset_at?: string;
            source?: string;
            freshness?: components["schemas"]["AttachedWorkerFreshnessV1"];
        };
        AttachedWorkerResourceV1: {
            state: string;
            resource_ref?: string;
            credential_state: string;
            entitlement_state: string;
            quota: components["schemas"]["AttachedWorkerQuotaObservationV1"];
        };
        AttachedWorkerCancelRequestV1: {
            state: string;
            revision?: components["schemas"]["AttachedWorkerUint64V1"];
            /** Format: date-time */
            requested_at?: string;
            /** Format: date-time */
            ack_deadline?: string;
        };
        AttachedWorkerCancelAcknowledgementV1: {
            state: string;
            revision?: components["schemas"]["AttachedWorkerUint64V1"];
            /** Format: date-time */
            acknowledged_at?: string;
        };
        AttachedWorkerProcessObservationV1: {
            state: string;
            attempt_id?: string;
            lease_generation?: components["schemas"]["AttachedWorkerUint64V1"];
            fence_fingerprint?: string;
            source: string;
            /** Format: date-time */
            observed_at?: string;
            freshness: components["schemas"]["AttachedWorkerFreshnessV1"];
        };
        AttachedWorkerTerminalEvidenceV1: {
            state: string;
            sequence?: components["schemas"]["AttachedWorkerUint64V1"];
            status?: string;
            evidence_fingerprint?: string;
        };
        AttachedWorkerCanonicalTerminalV1: {
            state: string;
            /** Format: date-time */
            committed_at?: string;
            sequence?: components["schemas"]["AttachedWorkerUint64V1"];
            status?: string;
        };
        AttachedWorkerExecutionV1: {
            state: string;
            run_id?: string;
            attempt_id?: string;
            lease_id?: string;
            lease_generation?: components["schemas"]["AttachedWorkerUint64V1"];
            fence_fingerprint?: string;
            /** Format: date-time */
            lease_expires_at?: string;
            cancel_request: components["schemas"]["AttachedWorkerCancelRequestV1"];
            cancel_ack: components["schemas"]["AttachedWorkerCancelAcknowledgementV1"];
            process_observation: components["schemas"]["AttachedWorkerProcessObservationV1"];
            worker_terminal: components["schemas"]["AttachedWorkerTerminalEvidenceV1"];
            canonical_terminal: components["schemas"]["AttachedWorkerCanonicalTerminalV1"];
        };
        AttachedWorkerAvailableActionV1: {
            code: components["schemas"]["AttachedWorkerActionCodeV1"];
            enabled: boolean;
            reason_code?: components["schemas"]["AttachedWorkerActionUnavailableCodeV1"];
            confirmation?: string;
        };
        AttachedWorkerGovernanceV1: {
            admission_control: string;
            remote_erase: string;
            available_actions: components["schemas"]["AttachedWorkerAvailableActionV1"][];
        };
        AttachedWorkerReadModelV1: {
            /** @constant */
            version: 1;
            /** Format: date-time */
            evaluated_at: string;
            worker: components["schemas"]["AttachedWorkerIdentityRecordV1"];
            identity: components["schemas"]["AttachedWorkerIdentityV1"];
            readiness: components["schemas"]["AttachedWorkerReadinessV1"];
            connectivity: components["schemas"]["AttachedWorkerConnectivityV1"];
            capability: components["schemas"]["AttachedWorkerCapabilityV1"];
            admission_preview: components["schemas"]["AttachedWorkerAdmissionPreviewV1"];
            observation_warnings: components["schemas"]["AttachedWorkerReasonCodeV1"][];
            resource: components["schemas"]["AttachedWorkerResourceV1"];
            execution: components["schemas"]["AttachedWorkerExecutionV1"];
            governance: components["schemas"]["AttachedWorkerGovernanceV1"];
        };
        AttachedWorkerSummaryV1: {
            /** Format: date-time */
            evaluated_at: string;
            worker: components["schemas"]["AttachedWorkerIdentityRecordV1"];
            connectivity: components["schemas"]["AttachedWorkerConnectivityV1"];
            execution_state: string;
            observation_warnings: components["schemas"]["AttachedWorkerReasonCodeV1"][];
        };
        AttachedWorkerListV1: {
            /** @constant */
            version: 1;
            /** Format: date-time */
            evaluated_at: string;
            items: components["schemas"]["AttachedWorkerSummaryV1"][];
            next_worker_id?: string;
            has_more: boolean;
        };
        /** @enum {string} */
        AttachedWorkerDiagnosticCohortV1: "identity" | "readiness" | "connectivity" | "eligibility" | "execution" | "governance";
        /** @enum {string} */
        AttachedWorkerDiagnosticCodeV1: "desired_state" | "observed_state" | "enrollment_state" | "daemon_state" | "last_daemon_failure" | "credential_state" | "isolation_configuration" | "isolation_verification" | "connection_state" | "last_contact" | "transport_failure" | "capability_state" | "admission_preview" | "entitlement_state" | "quota_state" | "attempt_state" | "cancel_request" | "cancel_ack" | "process_observation" | "worker_terminal" | "canonical_terminal" | "admission_control" | "remote_erase";
        AttachedWorkerDiagnosticFactV1: {
            cohort: components["schemas"]["AttachedWorkerDiagnosticCohortV1"];
            code: components["schemas"]["AttachedWorkerDiagnosticCodeV1"];
            state: string;
            /** Format: date-time */
            observed_at?: string;
            freshness?: components["schemas"]["AttachedWorkerFreshnessV1"];
        };
        AttachedWorkerDiagnosticsV1: {
            /** @constant */
            version: 1;
            /** Format: date-time */
            evaluated_at: string;
            worker_id: string;
            facts: components["schemas"]["AttachedWorkerDiagnosticFactV1"][];
            warnings: components["schemas"]["AttachedWorkerReasonCodeV1"][];
        };
        ArtifactCapability: {
            name: string;
            media_type: string;
            size: number;
            download: components["schemas"]["DownloadCapability"];
        };
    };
    responses: {
        /** @description Safe public error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Current authorized identity */
        Identity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Identity"];
            };
        };
        /** @description Canonical session */
        Session: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SessionSummary"];
            };
        };
        /** @description Run observation */
        Run: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Run"];
            };
        };
        /** @description Accepted canonical message */
        Message: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CreateMessageResponse"];
            };
        };
        /** @description Ephemeral upload capability */
        UploadIntent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UploadIntent"];
            };
        };
        /** @description Ephemeral download capability */
        Download: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DownloadCapability"];
            };
        };
    };
    parameters: {
        SessionID: string;
        RunID: string;
        WorkerID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Identity"];
            default: components["responses"]["Error"];
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    selectTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectTenantRequest"];
            };
        };
        responses: {
            200: components["responses"]["Identity"];
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                status?: components["schemas"]["SessionStatus"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            201: components["responses"]["Session"];
            default: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                cursor?: string;
                after_sequence?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered canonical events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    setSessionArchived: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveSessionRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            default: components["responses"]["Error"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageRequest"];
            };
        };
        responses: {
            200: components["responses"]["Message"];
            201: components["responses"]["Message"];
            default: components["responses"]["Error"];
        };
    };
    getComputeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential-free compute availability for this session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            200: components["responses"]["UploadIntent"];
            201: components["responses"]["UploadIntent"];
            default: components["responses"]["Error"];
        };
    };
    commitUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitUploadRequest"];
            };
        };
        responses: {
            /** @description Committed upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadCommit"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Run"];
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getAttachmentCapability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                sequence: number;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Download"];
            default: components["responses"]["Error"];
        };
    };
    getArtifactCapability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionID"];
                run_id: components["parameters"]["RunID"];
                manifest_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact metadata and capability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactCapability"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAttachedWorkers: {
        parameters: {
            query?: {
                after_worker_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped attached workers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachedWorkerListV1"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAttachedWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worker_id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped attached-worker read model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachedWorkerReadModelV1"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAttachedWorkerDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worker_id: components["parameters"]["WorkerID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded redacted attached-worker diagnostics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachedWorkerDiagnosticsV1"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
