output "folder_id" { value = module.foundation.folder_id }
output "dns_zone_id" { value = module.foundation.dns_zone_id }
output "dns_zone_name" { value = module.foundation.dns_zone_name }
output "registry_id" { value = module.foundation.registry_id }
output "repository_names" { value = module.foundation.repository_names }
output "image_publisher_service_account_id" { value = module.foundation.image_publisher_service_account_id }
output "release_publisher_service_account_id" { value = module.foundation.release_publisher_service_account_id }
output "release_publisher_federation_id" { value = module.foundation.release_publisher_federation_id }
output "registry_cleaner_service_account_id" { value = module.foundation.registry_cleaner_service_account_id }
output "registry_cleaner_federation_id" { value = module.foundation.registry_cleaner_federation_id }
output "github_oidc_audience" { value = module.foundation.github_oidc_audience }
output "github_oidc_subject" { value = module.foundation.github_oidc_subject }
output "github_release_oidc_subject" { value = module.foundation.github_release_oidc_subject }
output "ydb_connection_string" { value = module.foundation.ydb_connection_string }
output "artifact_bucket_name" { value = module.foundation.artifact_bucket_name }
output "dispatch_queue_url" { value = module.foundation.dispatch_queue_url }
output "delivery_queue_url" { value = module.foundation.delivery_queue_url }
output "scheduler_wake_queue_url" { value = module.foundation.scheduler_wake_queue_url }
output "telegram_secret_id" { value = module.foundation.telegram_secret_id }
output "web_bff_secret_id" { value = module.foundation.web_bff_secret_id }
output "gateway_service_account_id" { value = module.foundation.service_account_ids["gateway"] }
output "runtime_log_group_id" { value = module.foundation.log_group_id }
output "queue_provisioner_secret_id" { value = module.foundation.queue_provisioner_secret_id }
output "queue_provisioner_secret_version_id" { value = module.foundation.queue_provisioner_secret_version_id }
output "scheduler_ymq_secret_id" { value = module.foundation.scheduler_ymq_secret_id }
output "scheduler_ymq_secret_version_id" { value = module.foundation.scheduler_ymq_secret_version_id }
output "api_fqdn" { value = module.edge.api_fqdn }
output "api_url" { value = module.edge.api_url }
output "gateway_id" { value = module.edge.gateway_id }
output "web_fqdn" { value = module.web.fqdn }
output "web_url" { value = module.web.url }
output "web_gateway_id" { value = module.web.gateway_id }
output "web_certificate_id" { value = module.web.certificate_id }
output "web_container_id" { value = module.web.container_id }
output "web_container_url" { value = module.web.container_url }
output "web_container_revision_id" { value = module.web.container_revision_id }
output "web_image_ref" { value = module.web.image_ref }
output "web_prepared_instances" { value = module.web.prepared_instances }
output "web_concurrency" { value = module.web.concurrency }
output "control_slots" { value = module.runtime.control_container_ids }
output "control_slot_urls" { value = module.runtime.control_container_urls }
output "stable_slot" { value = module.edge.stable_slot }
output "candidate_slot" { value = module.edge.candidate_slot }
output "canary_weight" { value = module.edge.canary_weight }
output "budget_id" { value = var.budget_id }
output "registry_gc_inventory" {
  value = {
    schema_version   = 1
    environment      = "cloud-dev"
    lock_environment = "cloud-dev"
    folder_id        = module.foundation.folder_id
    registry_id      = module.foundation.registry_id
    stable_slot      = module.edge.stable_slot
    candidate_slot   = module.edge.candidate_slot
    repositories = {
      for name, repository_name in module.foundation.repository_names : name => {
        id   = module.foundation.repository_ids[name]
        name = repository_name
      }
    }
    containers              = merge(module.runtime.registry_gc_container_inventory, module.web.registry_gc_container_inventory)
    lifecycle_policy_status = module.foundation.registry_lifecycle_policy_statuses
  }
}
