package ports

import (
	"context"
	"errors"
	"time"

	"gitcode.com/urandon/sessionless/internal/domain"
	"gitcode.com/urandon/sessionless/internal/webcontract"
)

var ErrRunExplanationNotFound = errors.New("run explanation not found")
var ErrRunExplanationUnavailable = errors.New("run explanation temporarily unavailable")

// RunExplanationAuthorizationV1 is resolved by the server, never by a client.
// The resource transaction rechecks all fields without refreshing activity.
type RunExplanationAuthorizationV1 struct {
	TenantID                  domain.TenantID
	UserID                    domain.UserID
	MembershipSecurityVersion uint64
	WebSessionDigest          domain.SecretDigest
}

type RunExplanationReadStoreV1 interface {
	ReadRunExplanationV1(context.Context, RunExplanationAuthorizationV1, domain.RunID) (webcontract.RunExplanationV1, error)
}

type RunExplanationReadOutcomeKindV1 string

const (
	RunExplanationReadSuccessV1     RunExplanationReadOutcomeKindV1 = "success"
	RunExplanationReadNotFoundV1    RunExplanationReadOutcomeKindV1 = "not_found"
	RunExplanationReadRateLimitedV1 RunExplanationReadOutcomeKindV1 = "rate_limited"
)

// RunExplanationReadOutcomeV1 is published only after a confirmed transaction
// commit. In particular an opaque not-found consumes its authorized rate debit.
// This is an internal result, not another public response or authorization token.
type RunExplanationReadOutcomeV1 struct {
	Kind        RunExplanationReadOutcomeKindV1
	Explanation *webcontract.RunExplanationV1
	RetryAfter  time.Duration
}

func (value RunExplanationReadOutcomeV1) Validate() error {
	switch value.Kind {
	case RunExplanationReadSuccessV1:
		if value.Explanation == nil || value.Explanation.Validate() != nil || value.RetryAfter != 0 {
			return ErrRunExplanationUnavailable
		}
	case RunExplanationReadNotFoundV1:
		if value.Explanation != nil || value.RetryAfter != 0 {
			return ErrRunExplanationUnavailable
		}
	case RunExplanationReadRateLimitedV1:
		if value.Explanation != nil || value.RetryAfter <= 0 || value.RetryAfter > 5*time.Second || value.RetryAfter%time.Second != 0 {
			return ErrRunExplanationUnavailable
		}
	default:
		return ErrRunExplanationUnavailable
	}
	return nil
}

// RunExplanationRatedReadStoreV1 resolves canonical READ identity and tenant
// from the server's cookie digest inside its sole resource transaction. The
// request ID is generated by the BFF and cannot come from a client header.
// It writes only bounded shared rate/debit receipts, never session activity.
type RunExplanationRatedReadStoreV1 interface {
	ReadRatedRunExplanationV1(context.Context, domain.SecretDigest, string, domain.RunID) (RunExplanationReadOutcomeV1, error)
}
