include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

rest-stats {
  enabled = true
  bind-port = 9325
  bind-hostname = "0.0.0.0"
}

generate-node-address = false

aws {
  region = us-east-1
  accountId = 000000000000
}

queues {
  sessionless-dispatch {
    defaultVisibilityTimeout = 5 seconds
  }
  sessionless-delivery {
    defaultVisibilityTimeout = 5 seconds
  }
  sessionless-scheduler-wake {
    defaultVisibilityTimeout = 5 seconds
  }
  sessionless-dlq {
    defaultVisibilityTimeout = 5 seconds
  }
}
