-- +goose Up
ALTER TABLE `runs` SET (
    AUTO_PARTITIONING_BY_SIZE = ENABLED,
    AUTO_PARTITIONING_PARTITION_SIZE_MB = 512,
    AUTO_PARTITIONING_BY_LOAD = ENABLED,
    AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 1,
    AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 256
);

-- +goose Down
-- Production down migrations are intentionally disabled. See migrations/ydb/README.md.
